### ISSUE TITLE
postMessage throws an error when invoked from DIDConnect page

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1247]
```
DIDConnect.vue:146 failed to connect DOMException: Failed to execute 'postMessage' on 'Worker': #<Object> could not be cloned.
    at https://wallet.dev.trustbloc.dev/js/chunk-vendors.b481f22a.js:1:1540
    at new Promise (<anonymous>)
    at o (https://wallet.dev.trustbloc.dev/js/chunk-vendors.b481f22a.js:1:1245)
    at Proxy.connect (https://wallet.dev.trustbloc.dev/js/chunk-vendors.b481f22a.js:1:16063)
    at t.connect (https://wallet.dev.trustbloc.dev/js/chunk-vendors.b481f22a.js:1:37686)
    at f.connect (https://wallet.dev.trustbloc.dev/js/chunk-vendors.b481f22a.js:1:39226)
    at async ie.connect (https://wallet.dev.trustbloc.dev/js/263.e96ae69e.js:9:100248)
    at async Proxy.connect (https://wallet.dev.trustbloc.dev/js/Get-vue.fd932927.js:1:8202)
```

**Comment by birtony** [comment]
Fixed in https://github.com/trustbloc/wallet/pull/1249
