### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet#1580]
```
Error: waitUntil condition failed with the following reason: element ("iframe") still not existing after 60000ms
    at /home/runner/work/wallet/wallet/test/ui-automation/node_modules/webdriverio/build/commands/browser/waitUntil.js:70:15
    at Browser.wrapCommandFn (/home/runner/work/wallet/wallet/test/ui-automation/node_modules/@wdio/utils/build/shim.js:131:29)
    at _getThirdPartyLogin (/home/runner/work/wallet/wallet/test/ui-automation/test/helpers/wallet.js:249:5)
    at _getSignUp (/home/runner/work/wallet/wallet/test/ui-automation/test/helpers/wallet.js:177:3)
    at Object.exports.signUp (/home/runner/work/wallet/wallet/test/ui-automation/test/helpers/wallet.js:20:3)
    at Context.<anonymous> (/home/runner/work/wallet/wallet/test/ui-automation/test/specs/credential-interaction-flow.js:256:5)

```
https://github.com/trustbloc/wallet/runs/5570997684?check_suite_focus=true#step:4:2171

**Comment by rolsonquadras** [comment]
This has been fixed.
